/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulesRouteRouteImport } from './routes/schedules/route'
import { Route as HistoryRouteRouteImport } from './routes/history/route'
import { Route as AutoLauncherRunsRouteRouteImport } from './routes/auto-launcher-runs/route'
import { Route as IndexRouteImport } from './routes/index'

const SchedulesRouteRoute = SchedulesRouteRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRouteRoute = HistoryRouteRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoLauncherRunsRouteRoute = AutoLauncherRunsRouteRouteImport.update({
  id: '/auto-launcher-runs',
  path: '/auto-launcher-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-launcher-runs': typeof AutoLauncherRunsRouteRoute
  '/history': typeof HistoryRouteRoute
  '/schedules': typeof SchedulesRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-launcher-runs': typeof AutoLauncherRunsRouteRoute
  '/history': typeof HistoryRouteRoute
  '/schedules': typeof SchedulesRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-launcher-runs': typeof AutoLauncherRunsRouteRoute
  '/history': typeof HistoryRouteRoute
  '/schedules': typeof SchedulesRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auto-launcher-runs' | '/history' | '/schedules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auto-launcher-runs' | '/history' | '/schedules'
  id: '__root__' | '/' | '/auto-launcher-runs' | '/history' | '/schedules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoLauncherRunsRouteRoute: typeof AutoLauncherRunsRouteRoute
  HistoryRouteRoute: typeof HistoryRouteRoute
  SchedulesRouteRoute: typeof SchedulesRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-launcher-runs': {
      id: '/auto-launcher-runs'
      path: '/auto-launcher-runs'
      fullPath: '/auto-launcher-runs'
      preLoaderRoute: typeof AutoLauncherRunsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoLauncherRunsRouteRoute: AutoLauncherRunsRouteRoute,
  HistoryRouteRoute: HistoryRouteRoute,
  SchedulesRouteRoute: SchedulesRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
